---

- name: Deploy Web Server Playbook
  gather_facts: false
  hosts: all
  become: yes
  tasks:
    - name: "Download artifact"
      shell: |
        az login --identity
        rm -rf /var/www/*
        az storage blob download --auth-mode login -c {{ container_name }} -f /var/www/build.tar.gz -n {{ file_name }} --account-name ikstorageexample
        az logout

    - name: "Wait until the download finish"
      wait_for:
        path: /var/www/build.tar.gz

    - name: "unarchive package"
      unarchive:
        src: /var/www/build.tar.gz
        dest: /var/www
        remote_src: yes

    - name: "move unarchived package and delete unnecessary files"
      shell: |
        mv /var/www/build /var/www/html
        rm /var/www/build.tar.gz