---

- name: Web Server Playbook
  gather_facts: false
  hosts: all
  become: yes
  tasks:

    - name: "Download and install the Microsoft signing key"
      shell:
        cmd: "curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null"

    - name: "Add the Azure CLI software repository"
      shell:
        cmd: "echo 'deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ focal main' | sudo tee /etc/apt/sources.list.d/azure-cli.list"

    - name: "apt-get update"
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: "install nginx"
      apt:
        name: ['nginx']
        state: latest

    - name: "start nginx"
      systemd:
        state: started
        name: nginx

    - name: "install azure-cli pre-req"
      apt:
        name: ['ca-certificates', 'curl', 'apt-transport-https', 'lsb-release', 'gnupg']
        state: latest

    - name: "Install the azure-cli package"
      apt:
        name: ['azure-cli']
        state: latest

    - name: "Check ssh-key"
      stat:
        path: "/home/azureuser/.ssh/jenkins.pub"
      register: ssh_exist

    - name: "download jenkins public key and install"
      become: yes
      become_method: su
      become_user: azureuser
      shell: |
        az login --identity
        az storage blob download --auth-mode login -c public-key -f ~/jenkins.pub -n id_rsa.pub --account-name ikstorageexample
        az logout
        cat ~/jenkins.pub >> ~/.ssh/authorized_keys
      when: not ssh_exist.stat.exists